<a href="https://colab.research.google.com/github/wallis05/Python/blob/main/Class_2_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Condition Statements**

In [ ]:
# Condition Equal

a = 5
a == 6

False

In [ ]:
# Greater than Sign

i = 6
i > 5

True

In [ ]:
# Greater than Sign

i = 2
i > 5

False

In [ ]:
# Inequality Sign

i = 2
i != 6

True

In [ ]:
# Use Equality Sign to compare the strings

"ACDC" == "Michael Jackson"

False

**in the following cell Python compare ASCII code for those two letters**

In [ ]:
'B' > 'A'

True

In [ ]:
# Compare Characters

'BA' > 'AB'

True

Branching:



In [ ]:
# If statement example
age = 19
#age = 18

#expression that can be true or false
if age > 18:
    
    #within an indent, we have the expression that is run if the condition is true
    print("you can enter" )

#The statements after the if statement will run regardless if the condition is true or false 
print("move on")

you can enter
move on


In [ ]:
# If statement example
age = 19
age = 18

#expression that can be true or false
if age > 18:
    
    #within an indent, we have the expression that is run if the condition is true
    print("you can enter" )

#The statements after the if statement will run regardless if the condition is true or false 
print("move on")

move on


In [ ]:
# Else statement example

age = 18
# age = 19

if age > 18:
    print("you can enter" )
else:
    print("go see Meat Loaf" )
    
print("move on")

go see Meat Loaf
move on


In [ ]:
# Else statement example

age = 18
age = 19

if age > 18:
    print("you can enter" )
else:
    print("go see Meat Loaf" )
    
print("move on")

you can enter
move on


**Elif uses for multiple conditions**

In [ ]:
# Elif statment example

age = 18

if age > 18:
    print("you can enter" )
elif age == 18:
    print("go see Pink Floyd")
else:
    print("go see Meat Loaf" )
    
print("move on")

go see Pink Floyd
move on


**Logical Operations**  
and  
or  
not

A: 2 > 4 ---> Bool(A) = False

B: 17 > 10 ---> Bool(B) = True

In [ ]:
# Condition statement example ---> and

album_year = 1980

if (album_year > 1979) and (album_year < 1990):
    print ("Album year was in between 1980 and 1989")
    
print("")
print("Do Stuff..")

Album year was in between 1980 and 1989

Do Stuff..


In [ ]:
# Condition statement example ---> or

album_year = 1990

if (album_year < 1980) or (album_year > 1989):
    print ("Album was not made in the 1980's")
else:
    print("The Album was made in the 1980's ")

Album was not made in the 1980's


In [ ]:
# Condition statement example ---> not

album_year = 1983

if not (album_year == 1984):
    print ("Album year is not 1984")

Album year is not 1984


**Loop**  
for loop  

while loop

**Range**

In [ ]:
range(3)

range(0, 3)

In [ ]:
list(range(3))

[0, 1, 2]

In [ ]:
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [ ]:
list(range(1,12,2))

[1, 3, 5, 7, 9, 11]

**for loop**  

uses when you know how many times you're going to repeat

In [ ]:
# For loop example  ---> uses when you know how many times you're going to repeat

dates = [1982,1980,1973]
N = len(dates)

for i in range(N):
  print(i)
  print(dates[i])
  print(80 * '=')

0
1982
1
1980
2
1973


In [ ]:
list(range(1,3))

[1, 2]

in Python we can directly access the elements in the list as follows:

In [ ]:
# Example of for loop, loop through list ---> This approach is better

dates = [1982,1980,1973]
for year in dates:
    print(year)

1982
1980
1973


In [ ]:
dates = [1982,1980,1973]
N = len(dates)

for i in range(N):
  print(dates[i])

1982
1980
1973


In [ ]:
# Use for loop to change the elements in list

squares = ['red', 'yellow', 'green', 'purple', 'blue']

for i in range(0,5):
   print("Before square ", i, 'is', squares[i])
   squares[i] = 'weight'
   print("After square ", i, 'is', squares[i])

Before square  0 is red
After square  0 is weight
Before square  1 is yellow
After square  1 is weight
Before square  2 is green
After square  2 is weight
Before square  3 is purple
After square  3 is weight
Before square  4 is blue
After square  4 is weight


In [ ]:
squares

['weight', 'weight', 'weight', 'weight', 'weight']

**while loop**  

uses when you do not know how many times you're going to repeat

In [ ]:
# while loop example  

dates = [1982 ,1980 ,1973, 2000]

i = 0
year = 0

while (year != 1973):
  year = dates[i]
  i = i + 1
  print(year)
  
print("It took", i, "repetitions to get out of loop.")

1982
1980
1973
It took 3 repetitions to get out of loop.


**Library**  
algorithm; values; fuctions; methods  

**method** is a specific type of task or fuction that is applied on a specific type of objects.

In [ ]:
# lower is only applied on a string objects
A = "ARASH"
A.lower()

'arash'

In [ ]:
# Import the libraries

# numpy library


import time
import sys
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# Create a python list
a = ["0", 1, "two", "3", 4]
a

['0', 1, 'two', '3', 4]

In [ ]:
#print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [ ]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
#print each element of numpy array

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [ ]:
#check data type

a.dtype

dtype('int64')

In [ ]:
# Create a numpy array

b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
#check data type

b.dtype

dtype('float64')

In [ ]:
# Create a numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [ ]:
c[0] = 100
c

array([100,   1,   2,   3,   4])

Slicing

In [ ]:
#Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [ ]:
#Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [ ]:
# Create the index list

select =[0, 2, 3]

In [ ]:
print(c)

[100   1   2 300 400]


In [ ]:
# Use list to select element

d = c[select]
d

array([100,   2, 300])

In [ ]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000,    400])

In [ ]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [ ]:
# Get the size of numpy array

a.size

5

In [ ]:
# Get the number of dimensions of numpy array

a.ndim

1

In [ ]:
# Get the shape/size of numpy array

a.shape

(5,)

In [ ]:
# Get the mean of numpy array

print(a)

mean = a.mean()
mean

[0 1 2 3 4]


2.0

In [ ]:
# Get the standard deviation of numpy array

standard_deviation = a.std()
standard_deviation

1.4142135623730951

In [ ]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [ ]:
max_b = b.max()
max_b

5

In [ ]:
min_b = b.min()
min_b

-1

In [ ]:
#array operation

u = np.array([1,0])
u

array([1, 0])

In [ ]:
v = np.array([0,1])
v

array([0, 1])

In [ ]:
#array operation

z = u + v
z

array([1, 1])

In [ ]:
# The value of pie

np.pi

3.141592653589793

Linespace

In [ ]:
# Maeup a numpy array within [-2, 2] and 5 elements

np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])

2D values/ 2D tables

In [ ]:
# Create a list

a =[[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [ ]:
# Convert list to numpy array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
A.ndim

2

In [ ]:
# Show the numpy array shape

A.shape

(3, 3)

In [ ]:
# Show the size of numpy array

A.size

9

In [ ]:
b = [1, 2, 3, 4]
b[0]

1

In [ ]:
# Access the element on the second row and third column

A[1, 2]

23

In [ ]:
# Create a matrix C

c = np.array([[1,1],[2,2],[3,3]])
c

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
# Get the trasposed of c

c.T

array([[1, 2, 3],
       [1, 2, 3]])

**Pandas**  

most important that allow us to explore manipulate visulized to describe statistics descriptive analysis

could have excel files, cvs files

Plug and Play

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
test_list = [100,200,300]
pd.Series(data=test_list)

0    100
1    200
2    300
dtype: int64

https://archive.ics.uci.edu/ml/datasets.php

In [ ]:
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

df = pd.read_csv(url)

df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [ ]:
iris = pd.read_csv(url, names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'])
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

**Analytics: **   
Descriptive analytics   
Predictive  analytics  
Prescriptive analytics 

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
iris.nunique()

sepal_length    35
sepal_width     23
petal_length    43
petal_width     22
species          3
dtype: int64