<a href="https://colab.research.google.com/github/wallis05/Python/blob/main/Copy_of_MPAc290_2nd_session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this session we will be talking about conditions, loops and some libraries that will be useful for the rest of the course.

## Condition Statements

Comparison operations compare some value or operand and, based on a condition, they produce a Boolean. When comparing two values you can use these operators:

<ul>
    <li>equal: <b>==</b></li>
    <li>not equal: <b>!=</b></li>
    <li>greater than: <b>></b></li>
    <li>less than: <b>&lt;</b></li>
    <li>greater than or equal to: <b>>=</b></li>
    <li>less than or equal to: <b>&lt;=</b></li>
</ul>

In [ ]:
# Condition Equal

a = 5
a == 6

False

In [ ]:
# Greater than Sign

i = 6
i > 5

True

In [ ]:
# Greater than Sign

i = 2
i > 5

False

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/CondsGreater.gif" width="650" />

In [ ]:
# Inequality Sign

i = 2
i != 6

True

In [ ]:
# Use Equality sign to compare the strings

"ACDC" == "Michael Jackson"

False

In [ ]:
# Use Inequality sign to compare the strings

"ACDC" != "Michael Jackson"

True

in the following cell Python compare ASCII code for those two letters

In [ ]:
'B' > 'A'

True

In [ ]:
# Compare characters

'BA' > 'AB'

True

Branching: 

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/CondsIf.gif" width="650" />

In [ ]:
# If statement example
age = 19
#age = 18

#expression that can be true or false
if age > 18:
    
    #within an indent, we have the expression that is run if the condition is true
    print("you can enter" )

#The statements after the if statement will run regardless if the condition is true or false 
print("move on")

you can enter
move on


In [ ]:
# If statement example
age = 19
age = 18

#expression that can be true or false
if age > 18:
    
    #within an indent, we have the expression that is run if the condition is true
    print("you can enter" )

#The statements after the if statement will run regardless if the condition is true or false 
print("move on")

move on


In [ ]:
# Else statement example

age = 18
# age = 19

if age > 18:
    print("you can enter" )
else:
    print("go see Meat Loaf" )
    
print("move on")

go see Meat Loaf
move on


In [ ]:
# Else statement example

age = 18
age = 19

if age > 18:
    print("you can enter" )
else:
    print("go see Meat Loaf" )
    
print("move on")

you can enter
move on


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/CondsElse.gif" width="650" />

In [ ]:
# Elif statment example

age = 18

if age > 18:
    print("you can enter" )
elif age == 18:
    print("go see Pink Floyd")
else:
    print("go see Meat Loaf" )
    
print("move on")

go see Pink Floyd
move on


<img src ="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/CondsElif.gif" width="650" />

As before, we can add an <code>else</code> block to the <code>if</code> block. The code in the <code>else</code> block will only be executed if the result is <b>False</b>.


<b>Syntax:</b> 

if (condition):
    # do something
else:
    # do something else

Logical Operations

Sometimes you want to check more than one condition at once. For example, you might want to check if one condition and another condition is **True**. Logical operators allow you to combine or modify conditions.
<ul>
    <li><code>and</code></li>
    <li><code>or</code></li>
    <li><code>not</code></li>
</ul>

These operators are summarized for two variables using the following truth tables: 

A: 2 > 4 --> Bool(A) = False

B: 17 > 10 --> Bool(B) = True

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/CondsTable.png" width="650" />

In [ ]:
# Condition statement example

album_year = 1980

if (album_year > 1979) and (album_year < 1990):
    print ("Album year was in between 1980 and 1989")
    
print("")
print("Do Stuff..")

Album year was in between 1980 and 1989

Do Stuff..


In [ ]:
# Condition statement example

album_year = 1990

if (album_year < 1980) or (album_year > 1989):
    print ("Album was not made in the 1980's")
else:
    print("The Album was made in the 1980's ")

Album was not made in the 1980's


In [ ]:
# Condition statement example

album_year = 1983

if not (album_year == 1984):
    print ("Album year is not 1984")

Album year is not 1984


### Loops

Sometimes, you might want to repeat a given operation many times. Repeated executions like this are performed by <b>loops</b>. We will look at two types of loops, <code>for</code> loops and <code>while</code> loops.

In [ ]:
range(3)

range(0, 3)

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsRange.png" width="300" />

In [ ]:
list(range(3))

[0, 1, 2]

In [ ]:
list(range(1,12))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [ ]:
list(range(1,12,2))

[1, 3, 5, 7, 9, 11]

The <code>for</code> loop enables you to execute a code block multiple times. For example, you would use this if you would like to print out every element in a list.    
Let's try to use a <code>for</code> loop to print all the years presented in the list <code>dates</code>:

In [ ]:
list(range(3))

[0, 1, 2]

In [ ]:
# For loop example

dates = [1982,1980,1973]
N = len(dates)

for i in range(N):
    #print(i)
    print(dates[i])
    #print(80*'=')

1982
1980
1973


In [ ]:
list(range(1,3))

[1, 2]

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsForRange.gif" width="800" />

In Python we can directly access the elements in the list as follows: 

In [ ]:
# Exmaple of for loop, loop through list
dates = [1982,1980,1973]
for year in dates:  
    print(year)   

1982
1980
1973


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsForList.gif" width="800">

In [ ]:
# For loop example

dates = [1982,1980,1973]
N = len(dates)

for i in range(N):
    print(dates[i])

1982
1980
1973


In [ ]:
# Use for loop to change the elements in list

squares = ['red', 'yellow', 'green', 'purple', 'blue']

for i in range(0, 5):
    print("Before square ", i, 'is',  squares[i])
    squares[i] = 'weight'
    print("After square ", i, 'is',  squares[i])

Before square  0 is red
After square  0 is weight
Before square  1 is yellow
After square  1 is weight
Before square  2 is green
After square  2 is weight
Before square  3 is purple
After square  3 is weight
Before square  4 is blue
After square  4 is weight


In [ ]:
squares

['weight', 'weight', 'weight', 'weight', 'weight']

What is while loop?

In [ ]:
# While Loop Example

dates = [1982, 1980, 1973, 2000]

i = 0
year = 0

while (year != 1973):
    year = dates[i]
    i = i + 1
    print(year)

print("It took ", i ,"repetitions to get out of loop.")

1982
1980
1973
It took  3 repetitions to get out of loop.


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsWhile.gif" width="650" />

In [ ]:
A = "Class"
A.lower()

'class'

Library

In [ ]:
# Import the libraries

import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

In [ ]:
# Plotting functions

def Plotvec1(u, z, v):
    ax = plt.axes()
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)
    plt.text(*(u + 0.1), 'u')
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)
    plt.text(*(v + 0.1), 'v')
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)


def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

In [ ]:
# Create a python list

a = ["0", 1, "two", "3", 4]

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumOneList.png" width="660" />

In [ ]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [ ]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumOneNp.png" width="500" />

In [ ]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [ ]:
a.dtype

dtype('int64')

In [ ]:
# Create a numpy array

b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.dtype

dtype('float64')

In [ ]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [ ]:
c[0] = 100

In [ ]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

In [ ]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [ ]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [ ]:
# Create the index list

select = [0, 2, 3]

In [ ]:
c

array([100,   1,   2, 300, 400])

In [ ]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300])

In [ ]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000,    400])

In [ ]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [ ]:
# Get the size of numpy array

a.size

5

In [ ]:
# Get the number of dimensions of numpy array

a.ndim

1

In [ ]:
# Get the shape/size of numpy array

a.shape

(5,)

In [ ]:
# Get the mean of numpy array

mean = a.mean()
mean

2.0

In [ ]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.4142135623730951

In [ ]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [ ]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

5

In [ ]:

min_b = b.min()
min_b

-1

In [ ]:
u = np.array([1, 0])
u

array([1, 0])

In [ ]:
v = np.array([0, 1])
v

array([0, 1])

In [ ]:
# Numpy Array Addition

z = u + v
z

array([1, 1])

In [ ]:
# The value of pie

np.pi

3.141592653589793

Linespace

In [ ]:
# Makeup a numpy array within [-2, 2] and 5 elements

np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])

In [ ]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [ ]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoEg.png" width="500" />

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFT.png" width="400" />

In [ ]:
A.ndim

2

In [ ]:
# Show the numpy array shape

A.shape

(3, 3)

In [ ]:
# Show the numpy array size

A.size

9

In [ ]:
b = [1,2,3,4]
b[0]

1

In [ ]:
# Access the element on the second row and third column

A[1, 2]

23

In [ ]:
# Access the element on the second row and third column

A[1][2]

23

In [ ]:
# Access the element on the first row and first column

A[0][0]

11

In [ ]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [ ]:
# Access the element on the first and second rows and third column

A[1:3, 2]

array([23, 33])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoTST.png" width="400" />

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoAdd.png" width="500" />

In [ ]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [ ]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [ ]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoDb.png" width="500" />

In [ ]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [ ]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [ ]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

# Pandas

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
test_list = [100,200,300]
pd.Series(data=test_list)

0    100
1    200
2    300
dtype: int64

Let's bring a dataset and see how we can use Pandas to learn more about it.
Here, we are going to use the Iris dataset from UCI Archive. https://archive.ics.uci.edu/ml/datasets/Iris

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

df = pd.read_csv(url)

df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [ ]:
iris = pd.read_csv(url, names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'])
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Analytics:
* descriptive analytics
* predictive analytics
* prescriptive analytics

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
iris.nunique()

sepal_length    35
sepal_width     23
petal_length    43
petal_width     22
species          3
dtype: int64

In [ ]:
iris['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
list_a = list(iris['sepal_length'])

In [ ]:
iris[['sepal_length', 'petal_length']]

sepal_length  petal_length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

**Conditional Selection**

We can also ***filter*** through the data. 

In [ ]:
iris[iris['petal_length'] > 1.6]

sepal_length  sepal_width  petal_length  petal_width         species
5             5.4          3.9           1.7          0.4     Iris-setosa
18            5.7          3.8           1.7          0.3     Iris-setosa
20            5.4          3.4           1.7          0.2     Iris-setosa
23            5.1          3.3           1.7          0.5     Iris-setosa
24            4.8          3.4           1.9          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[106 rows x 5 columns]

In [ ]:
iris[iris['species'] == 'Iris-setosa']

**Aggregation Functions**

Now that we know how to navigate through data, it is time to do some aggregation upon it. To start off, we can use the describe function to find out the distribution, max, minimum and useful statistics of our dataset.

In [ ]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
iris.max()

sepal_length               7.9
sepal_width                4.4
petal_length               6.9
petal_width                2.5
species         Iris-virginica
dtype: object

In [ ]:
iris['petal_width'].max()

2.5

In [ ]:
iris.std()

sepal_length    0.828066
sepal_width     0.433594
petal_length    1.764420
petal_width     0.763161
dtype: float64

In [ ]:
iris['petal_width'].median()

1.3

In [ ]:
iris.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000